[package]
name = "funding-service-design-account-store"
version = "0.1.1"
description = "The funding service design account store for the DLUHC."
authors = ["Version One", "HM Government, Department of Levelling Up, Housing and Communities"]
license = "MIT License"

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
count = true
extend-ignore = ["E203", "E704"]

[tool.isort]
profile = "black"
force_single_line = "true"
