"""empty message

Revision ID: 240995c9342b
Revises: 
Create Date: 2022-09-29 15:09:08.552799

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils # noqa


# revision identifiers, used by Alembic.
revision = '240995c9342b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'email', name=op.f('pk_account'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###
