"""empty message

Revision ID: 26906e63500c
Revises: 13d601bfaee1
Create Date: 2022-12-01 16:09:49.517914

"""
import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "26906e63500c"
down_revision = "13d601bfaee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("full_name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("azure_ad_subject_id", sa.String(), nullable=True)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_account_azure_ad_subject_id"),
            ["azure_ad_subject_id"],
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_account_email"), ["email"]
        )
        batch_op.create_unique_constraint(batch_op.f("uq_account_id"), ["id"])

    op.create_table(
        "role",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_role_account_id_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")
    sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype").drop(
        op.get_bind()
    )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_id"), type_="unique")
        batch_op.drop_constraint(
            batch_op.f("uq_account_email"), type_="unique"
        )
        batch_op.drop_constraint(
            batch_op.f("uq_account_azure_ad_subject_id"), type_="unique"
        )
        batch_op.drop_column("azure_ad_subject_id")
        batch_op.drop_column("full_name")

    # ### end Alembic commands ###
