"""empty message

Revision ID: c28cf5398424
Revises: efbc3ab28bdb
Create Date: 2022-09-26 11:58:56.309510

"""
import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "c28cf5398424"
down_revision = "efbc3ab28bdb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_application_relationship")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_application_relationship",
        sa.Column("account_id", sa.CHAR(length=32), nullable=False),
        sa.Column("application_id", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name="fk_account_application_relationship_account_id_account",
        ),
        sa.PrimaryKeyConstraint(
            "account_id",
            "application_id",
            name="pk_account_application_relationship",
        ),
    )
    # ### end Alembic commands ###
