"""empty message

Revision ID: d197951abf53
Revises: 13d601bfaee1
Create Date: 2022-11-28 12:34:32.129005

"""
import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d197951abf53"
down_revision = "13d601bfaee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_account_id"), ["id"])

    op.create_table(
        "role",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_role_account_id_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_id"), type_="unique")

    # ### end Alembic commands ###
