"""empty message

Revision ID: e355f9c4356b
Revises: 13d601bfaee1
Create Date: 2022-12-02 09:25:41.244199

"""

import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e355f9c4356b"
down_revision = "13d601bfaee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.add_column(sa.Column("full_name", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("azure_ad_subject_id", sa.String(), nullable=True)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_account_azure_ad_subject_id"),
            ["azure_ad_subject_id"],
        )
        batch_op.create_unique_constraint(batch_op.f("uq_account_email"), ["email"])
        batch_op.create_unique_constraint(batch_op.f("uq_account_id"), ["id"])

    op.create_table(
        "role",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "role",
            sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_role_account_id_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")

    sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype").drop(
        op.get_bind()
    )

    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_account_id"), type_="unique")
        batch_op.drop_constraint(batch_op.f("uq_account_email"), type_="unique")
        batch_op.drop_constraint(
            batch_op.f("uq_account_azure_ad_subject_id"), type_="unique"
        )
        batch_op.drop_column("azure_ad_subject_id")
        batch_op.drop_column("full_name")
    # ### end Alembic commands ###
