"""empty message

Revision ID: efbc3ab28bdb
Revises: 13d601bfaee1
Create Date: 2022-09-20 17:10:11.598232

"""
import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "efbc3ab28bdb"
down_revision = "13d601bfaee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_application_relationship",
        sa.Column(
            "account_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column("application_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f(
                "fk_account_application_relationship_account_id_account"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "account_id",
            "application_id",
            name=op.f("pk_account_application_relationship"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("account_application_relationship")
    # ### end Alembic commands ###
