"""empty message

Revision ID: f12096543d09
Revises: 13d601bfaee1
Create Date: 2022-11-28 09:40:59.516495

"""
import sqlalchemy as sa
import sqlalchemy_utils  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f12096543d09"
down_revision = "13d601bfaee1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum("LEAD_ASSESSOR", "ASSESSOR", "COMMENTER", name="roletype"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
            name=op.f("fk_role_account_id_account"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role")
    # ### end Alembic commands ###
