name: Bump tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  bump-tag:
    if: ${{ github.actor != 'dependabot[bot]' }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/bump-tag.yml@main   