name: Copilot Workflows
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
        environment:
          description:  Which AWS Account to use
          type: choice
          required: true
          options:
          - test
        # Shared workflow consideration
        # application:
        #   description:  Application Name
        #   type: string/choice
        # - notification
        #   required: true
        init:
          description: Initialise the application?
          type: boolean
          default: false
        service:
          description: Service Name
          type: string
          required: true
          default: 'funding-service-design-account-store'
        port:
          description: Access port
          type: string
          default: '80'
        type:
          description: Type of service to deploy
          type: choice
          options:
          - 'Backend Service'
          - 'Load Balanced Web Service'
          - 'Request-Driven Web Service'
          - 'Scheduled Job'
          - 'Worker Service'
          default: 'Backend Service'


jobs:
  deployment:
    concurrency: deploy-${{ inputs.environment || 'test' }} # Forces only one workflow at a time can run on the environment
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'test' }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Get current date
        id: currentdatetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/GitHubPushToECR
          role-session-name: NOTIFICATION_COPILOT_${{ steps.currentdatetime.outputs.datetime }}
          aws-region: eu-west-2

      - name: Install AWS Copilot CLI
        run: |
          curl -Lo aws-copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux && chmod +x aws-copilot && sudo mv aws-copilot /usr/local/bin/copilot

      - name: Inject Git SHA into manifest
        run: |
          yq -i '.variables.GITHUB_SHA = "${{ github.sha }}"'  copilot/backend/manifest.yml

      - name: Inject GOV Notify API Key
        run: |
          yq -i '.variables.GOV_NOTIFY_API_KEY = "${{ secrets.GOV_NOTIFY_API_KEY }}"' copilot/backend/manifest.yml

      - name: Copilot init
        if: ${{ inputs.init == true }}
        run: |
          copilot init \
            --name ${{ inputs.service }} \
            --app notification \
            --type ${{ inputs.type }} \
            --image 'ghcr.io/communitiesuk/funding-service-account-store' \
            --port ${{ inputs.port }} \
            --deploy

      - name: Copilot deploy
        if: ${{ inputs.init == false }} # Only do this if not initialising - init includes deploy
        run: |
          copilot deploy --env ${{ inputs.environment || 'test' }}
