name: Deploy to Gov PaaS

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'

jobs:
  test_and_deploy:
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/deploy.yml@fs-1972-add-uat-tests
    with:
      app_name: ${{ github.event.repository.name }}
      api: true
      upgrade_db: true
    if: ${{ github.actor != 'dependabot[bot]' }}
    secrets:
      CF_API: ${{secrets.CF_API}}
      CF_ORG: ${{secrets.CF_ORG}}
      CF_SPACE: ${{secrets.CF_SPACE}}
      CF_USER: ${{secrets.CF_USER}}
      CF_PASSWORD: ${{secrets.CF_PASSWORD}}
      E2E_PAT: ${{secrets.E2E_PAT}}
